### upload file
POST {{base_url}}/api/media/v1/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFm7xUq889QiCjy9U

------WebKitFormBoundaryFm7xUq889QiCjy9U
Content-Disposition: form-data; name="files"; filename="1_crop.jpeg"
Content-Type: image/jpeg

< ../sample/1_crop.jpeg
------WebKitFormBoundaryFm7xUq889QiCjy9U--

### get upload page
GET {{base_url}}/api/media/v1/page
Content-Type: text/html