### upload file
POST {{base_url}}/api/media/v1/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFm7xUq889QiCjy9U

------WebKitFormBoundaryFm7xUq889QiCjy9U
Content-Disposition: form-data; name="files"; filename="sample.mp3"
Content-Type: audio/mpeg

< /Users/hans/samples/audio.mp3
------WebKitFormBoundaryFm7xUq889QiCjy9U--

### get upload page
GET {{base_url}}/api/media/v1/page
Content-Type: text/html

### get media
GET {{base_url}}/api/media/v1/MEDIA_a9d33910847d11efbbaeacde48001122
